version = 1

test_patterns = [
  "src/tests/**",
  "**.test.**"
]

exclude_patterns = [
  ".github/**",
  "public/**"
]

[[analyzers]]
name = "javascript"
enabled = true

  [analyzers.meta]
  plugins = ["react"]